library:
  source-dirs: src
tests:
  echobot-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echobot
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- text
- bytestring
- hs-aitubots-api
- http-client
- http-client-tls
- base >= 4.7 && < 5
name: echobot
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/echobot
license: BSD3
executables:
  echobot-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echobot
description: Please see the README on GitHub at <https://github.com/githubuser/echobot#readme>
