library:
  source-dirs: src
tests:
  hs-aitubots-api-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-aitubots-api
copyright: 2020 Ronin Research Group
maintainer: bg@purestack.org
dependencies:
- optparse-applicative
- hspec
- time
- uuid
- uuid-types
- bytestring
- http-types
- aeson
- http-client-tls
- http-client
- text
- async
- mtl
- base >= 4.7 && < 5
name: hs-aitubots-api
version: 0.3.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Boris Glebov
github: avatar29A/hs-aitubots-api
license: BSD3
description: Please see the README on GitHub at <https://github.com/avatar29A/hs-aitubots-api/READMME.md>
