version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies.
          keys:
            - hs-aitubots-api-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - hs-aitubots-api-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack --no-terminal setup
      - run:
          name: Run tests
          command: stack test
      - run:
          name: Run integration-tests
          command: stack test --test-arguments "--integration --token ${AITU_BOT_TOKEN} --chatid ${AITU_BOT_CHAT_ID} --botName ${AITU_BOT_NAME}"
      - run:
          name: Install executable
          command: stack --no-terminal sdist
      - save_cache:
          name: Cache Dependencies
          key: hs-aitubots-api-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - store_artifacts:
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: ".stack-work/dist"
          destination: circleci-demo-haskell-exe